name: Scan for secrets

on:
  pull_request:
  push:
    branches:
      - develop
      - master

jobs:
  scan-for-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-infisical
      - name: Scan for secrets
        env:
          INFISICAL_TOKEN: ${{ secrets.INFISICAL_TOKEN_CI }}
        run: |
          export INFISICAL_TOKEN=${{ secrets.INFISICAL_TOKEN_CI }}
          infisical scan --verbose --redact
