name: 'Setup Infisical Action'
author: 'Beep boop'
description: 'Installs infisical in the runner and exports the INFISICAL_TOKEN.'

runs:
  using: 'composite'
  steps:
    - name: Install Infisical
      shell: bash
      run: |
        # Install Infisical CLI to inject environment variables
        curl -1sLf 'https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.deb.sh' | sudo -E bash
        sudo apt-get update && sudo apt-get install -y infisical

        # Ensure Infisical was installed
        infisical --version || exit 1
